// Map<String, Map<String, String>> data = {
//   "AFN": {"name": "Afghanistan", "symbol": ""},
//   "ALL": {"name": "Albania", "symbol": "L"},
//   "": {"name": "U.S. Virgin Islands", "symbol": ""},
//   "DZD": {"name": "Algeria", "symbol": "دج"},
//   "EUR": {"name": "Spain", "symbol": "€"},
//   "AOA": {"name": "Angola", "symbol": ""},
//   "XCD": {"name": "Saint Vincent and the Grenadines", "symbol": "EC\$"},
//   "AZN": {"name": "Azerbaijan", "symbol": ""},
//   "ARS": {"name": "Argentina", "symbol": "\$"},
//   "AUD": {"name": "Tuvalu", "symbol": "\$"},
//   "BSD": {"name": "Bahamas", "symbol": "B\$"},
//   "BHD": {"name": "Bahrain", "symbol": ".د.ب"},
//   "BDT": {"name": "Bangladesh", "symbol": "Tk"},
//   "AMD": {"name": "Armenia", "symbol": ""},
//   "BBD": {"name": "Barbados", "symbol": "BBD"},
//   "BTN": {"name": "Bhutan", "symbol": "Nu."},
//   "BOB": {"name": "Bolivia", "symbol": "Bs"},
//   "BAM": {"name": "Bosnia and Herzegovina", "symbol": ""},
//   "BWP": {"name": "Botswana", "symbol": "P"},
//   "BRL": {"name": "Brazil", "symbol": "R\$"},
//   "BZD": {"name": "Belize", "symbol": "BZ\$"},
//   "SBD": {"name": "Solomon Islands", "symbol": "SI\$"},
//   "BND": {"name": "Brunei", "symbol": "B\$"},
//   "BGN": {"name": "Bulgaria", "symbol": "лв"},
//   "MMK": {"name": "Myanmar [Burma]", "symbol": "K"},
//   "BIF": {"name": "Burundi", "symbol": "FBu"},
//   "BYN": {"name": "Belarus", "symbol": ""},
//   "KHR": {"name": "Cambodia", "symbol": "KHR"},
//   "XAF": {"name": "Gabon", "symbol": "BEAC"},
//   "CAD": {"name": "Canada", "symbol": "C\$"},
//   "KYD": {"name": "Cayman Islands", "symbol": "\$"},
//   "LKR": {"name": "Sri Lanka", "symbol": "ரூ"},
//   "CLP": {"name": "Chile", "symbol": "\$"},
//   "CNY": {"name": "China", "symbol": "¥"},
//   "TWD": {"name": "Taiwan", "symbol": "NT\$"},
//   "COP": {"name": "Colombia", "symbol": "\$"},
//   "KMF": {"name": "Comoros", "symbol": "KMF"},
//   "CDF": {"name": "Congo [DRC]", "symbol": ""},
//   "CRC": {"name": "Costa Rica", "symbol": "₡"},
//   "HRK": {"name": "Croatia", "symbol": "kn"},
//   "CUP": {"name": "Cuba", "symbol": "\$MN"},
//   "CZK": {"name": "Czech Republic", "symbol": "Kč"},
//   "XOF": {"name": "Burkina Faso", "symbol": "BCEAO"},
//   "DKK": {"name": "Denmark", "symbol": "kr"},
//   "DOP": {"name": "Dominican Republic", "symbol": "RD\$"},
//   "USD": {"name": "United States", "symbol": "\$"},
//   "ETB": {"name": "Ethiopia", "symbol": "Br"},
//   "ERN": {"name": "Eritrea", "symbol": ""},
//   "FJD": {"name": "Fiji", "symbol": "FJ\$"},
//   "XPF": {"name": "Wallis and Futuna", "symbol": "F"},
//   "DJF": {"name": "Djibouti", "symbol": "Fdj"},
//   "GEL": {"name": "Georgia", "symbol": ""},
//   "GMD": {"name": "Gambia", "symbol": "D"},
//   "GHS": {"name": "Ghana", "symbol": "GHS"},
//   "GIP": {"name": "Gibraltar", "symbol": ""},
//   "GTQ": {"name": "Guatemala", "symbol": "Q"},
//   "GNF": {"name": "Guinea", "symbol": "FG"},
//   "GYD": {"name": "Guyana", "symbol": "GY\$"},
//   "HTG": {"name": "Haiti", "symbol": ""},
//   "HNL": {"name": "Honduras", "symbol": "L"},
//   "HKD": {"name": "Hong Kong", "symbol": "HK\$"},
//   "HUF": {"name": "Hungary", "symbol": "Ft"},
//   "ISK": {"name": "Iceland", "symbol": "kr"},
//   "INR": {"name": "India", "symbol": "Rs."},
//   "IDR": {"name": "Indonesia", "symbol": "Rp"},
//   "IRR": {"name": "Iran", "symbol": ""},
//   "IQD": {"name": "Iraq", "symbol": "ع.د"},
//   "ILS": {"name": "Israel", "symbol": "₪"},
//   "JMD": {"name": "Jamaica", "symbol": ""},
//   "JPY": {"name": "Japan", "symbol": "¥"},
//   "KZT": {"name": "Kazakhstan", "symbol": "KZT"},
//   "JOD": {"name": "Jordan", "symbol": "JOD"},
//   "KES": {"name": "Kenya", "symbol": "KSh"},
//   "KPW": {"name": "North Korea", "symbol": "₩"},
//   "KRW": {"name": "South Korea", "symbol": "₩"},
//   "KWD": {"name": "Kuwait", "symbol": "د.ك"},
//   "KGS": {"name": "Kyrgyzstan", "symbol": "KGS"},
//   "LAK": {"name": "Laos", "symbol": ""},
//   "LBP": {"name": "Lebanon", "symbol": ""},
//   "LSL": {"name": "Lesotho", "symbol": ""},
//   "LVL": {"name": "Latvia", "symbol": ""},
//   "LRD": {"name": "Liberia", "symbol": ""},
//   "LYD": {"name": "Libya", "symbol": ""},
//   "CHF": {"name": "Switzerland", "symbol": "CHF"},
//   "MOP": {"name": "Macau", "symbol": "\$"},
//   "MGA": {"name": "Madagascar", "symbol": ""},
//   "MWK": {"name": "Malawi", "symbol": "MK"},
//   "MYR": {"name": "Malaysia", "symbol": "RM"},
//   "MVR": {"name": "Maldives", "symbol": "Rf"},
//   "MRO": {"name": "Mauritania", "symbol": "UM"},
//   "MUR": {"name": "Mauritius", "symbol": "₨"},
//   "MXN": {"name": "Mexico", "symbol": "\$"},
//   "MNT": {"name": "Mongolia", "symbol": "₮"},
//   "MDL": {"name": "Moldova", "symbol": "MDL"},
//   "MAD": {"name": "Morocco", "symbol": "د.م."},
//   "MZN": {"name": "Mozambique", "symbol": ""},
//   "OMR": {"name": "Oman", "symbol": "ر.ع."},
//   "NAD": {"name": "Namibia", "symbol": "N\$"},
//   "NPR": {"name": "Nepal", "symbol": "₨"},
//   "AWG": {"name": "Aruba", "symbol": "ƒ"},
//   "VUV": {"name": "Vanuatu", "symbol": "Vt"},
//   "NZD": {"name": "New Zealand", "symbol": "\$"},
//   "NIO": {"name": "Nicaragua", "symbol": "C\$"},
//   "NGN": {"name": "Nigeria", "symbol": "₦"},
//   "NOK": {"name": "Norway", "symbol": "kr"},
//   "PKR": {"name": "Pakistan", "symbol": "Rs."},
//   "PAB": {"name": "Panama", "symbol": "B"},
//   "PGK": {"name": "Papua New Guinea", "symbol": "K"},
//   "PYG": {"name": "Paraguay", "symbol": ""},
//   "PEN": {"name": "Peru", "symbol": "S/."},
//   "PHP": {"name": "Philippines", "symbol": "₱"},
//   "PLN": {"name": "Poland", "symbol": "zł"},
//   "QAR": {"name": "Qatar", "symbol": "ر.ق"},
//   "RON": {"name": "Romania", "symbol": "L"},
//   "RUB": {"name": "Russia", "symbol": "руб"},
//   "RWF": {"name": "Rwanda", "symbol": "RF"},
//   "SHP": {"name": "Saint Helena", "symbol": "£"},
//   "STD": {"name": "São Tomé and Príncipe", "symbol": "Db"},
//   "SAR": {"name": "Saudi Arabia", "symbol": "ر.س"},
//   "RSD": {"name": "Serbia", "symbol": ""},
//   "SCR": {"name": "Seychelles", "symbol": "SR"},
//   "SLL": {"name": "Sierra Leone", "symbol": "Le"},
//   "SGD": {"name": "Singapore", "symbol": "S\$"},
//   "VND": {"name": "Vietnam", "symbol": "₫"},
//   "SOS": {"name": "Somalia", "symbol": "So."},
//   "ZAR": {"name": "South Africa", "symbol": "R"},
//   "SDG": {"name": "Sudan", "symbol": "SDG"},
//   "SRD": {"name": "Suriname", "symbol": ""},
//   "SZL": {"name": "Swaziland", "symbol": "SZL"},
//   "SEK": {"name": "Sweden", "symbol": "kr"},
//   "SYP": {"name": "Syria", "symbol": "SYP"},
//   "TJS": {"name": "Tajikistan", "symbol": ""},
//   "THB": {"name": "Thailand", "symbol": "฿"},
//   "TOP": {"name": "Tonga", "symbol": "T\$"},
//   "TTD": {"name": "Trinidad and Tobago", "symbol": "TTD"},
//   "AED": {"name": "United Arab Emirates", "symbol": "د.إ"},
//   "TND": {"name": "Tunisia", "symbol": "د.ت"},
//   "TRY": {"name": "Turkey", "symbol": "YTL"},
//   "TMT": {"name": "Turkmenistan", "symbol": ""},
//   "UGX": {"name": "Uganda", "symbol": "USh"},
//   "UAH": {"name": "Ukraine", "symbol": ""},
//   "MKD": {"name": "Macedonia [FYROM]", "symbol": "MKD"},
//   "EGP": {"name": "Egypt", "symbol": "ج.م"},
//   "GBP": {"name": "United Kingdom", "symbol": "£"},
//   "TZS": {"name": "Tanzania", "symbol": "x"},
//   "UYU": {"name": "Uruguay", "symbol": "UYU"},
//   "UZS": {"name": "Uzbekistan", "symbol": "UZS"},
//   "VEF": {"name": "Venezuela", "symbol": "VEF"},
//   "WST": {"name": "Samoa", "symbol": "WS\$"},
//   "YER": {"name": "Yemen", "symbol": "YER"},
//   "ZMW": {"name": "Zambia", "symbol": ""}
// };

// class CurrencyData {
//   String name;
//   String symbol;
//   String code;
//   CurrencyData(this.name, this.symbol, this.code);
// }

// countryCurrency(String code) {
//   if (data[code] == null) return null;
//   return CurrencyData(
//     data[code]!['name']!,
//     data[code]!['symbol']!,
//     code,
//   );
// }
